// This file is auto-generated by @hey-api/openapi-ts

export const AIRequestSchema = {
    properties: {
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        },
        platform: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Platform'
                },
                {
                    type: 'null'
                }
            ]
        },
        date_from: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date From'
        },
        date_to: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date To'
        }
    },
    type: 'object',
    required: ['workspace_id'],
    title: 'AIRequest',
    description: 'Common fields for AI generation requests.'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ContentTypeSchema = {
    type: 'string',
    enum: ['post', 'reel', 'story', 'video', 'tweet', 'article', 'short'],
    title: 'ContentType'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InsightSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        type: {
            type: 'string',
            enum: ['positive', 'negative', 'neutral'],
            title: 'Type'
        },
        metric: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric'
        }
    },
    type: 'object',
    required: ['title', 'body', 'type'],
    title: 'Insight'
} as const;

export const InsightsResponseSchema = {
    properties: {
        insights: {
            items: {
                '$ref': '#/components/schemas/Insight'
            },
            type: 'array',
            title: 'Insights'
        },
        generated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Generated At'
        }
    },
    type: 'object',
    required: ['insights'],
    title: 'InsightsResponse'
} as const;

export const IntegrationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        },
        platform: {
            '$ref': '#/components/schemas/Platform'
        },
        status: {
            '$ref': '#/components/schemas/IntegrationStatus'
        },
        external_account_id: {
            type: 'string',
            title: 'External Account Id'
        },
        external_account_name: {
            type: 'string',
            title: 'External Account Name'
        },
        external_account_avatar: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Account Avatar'
        },
        last_synced_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Synced At'
        },
        sync_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sync Error'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'workspace_id', 'platform', 'status', 'external_account_id', 'external_account_name'],
    title: 'IntegrationPublic',
    description: 'Safe representation — never includes raw or encrypted tokens.'
} as const;

export const IntegrationStatusSchema = {
    type: 'string',
    enum: ['active', 'expired', 'error', 'disconnected'],
    title: 'IntegrationStatus'
} as const;

export const IntegrationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/IntegrationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'IntegrationsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MetricTotalsSchema = {
    properties: {
        impressions: {
            type: 'integer',
            title: 'Impressions',
            default: 0
        },
        reach: {
            type: 'integer',
            title: 'Reach',
            default: 0
        },
        views: {
            type: 'integer',
            title: 'Views',
            default: 0
        },
        clicks: {
            type: 'integer',
            title: 'Clicks',
            default: 0
        },
        engagements: {
            type: 'integer',
            title: 'Engagements',
            default: 0
        },
        likes: {
            type: 'integer',
            title: 'Likes',
            default: 0
        },
        comments: {
            type: 'integer',
            title: 'Comments',
            default: 0
        },
        shares: {
            type: 'integer',
            title: 'Shares',
            default: 0
        },
        saves: {
            type: 'integer',
            title: 'Saves',
            default: 0
        },
        followers_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Followers Count'
        },
        followers_gained: {
            type: 'integer',
            title: 'Followers Gained',
            default: 0
        }
    },
    type: 'object',
    title: 'MetricTotals',
    description: 'Aggregated metric totals over a date range.'
} as const;

export const MetricsSummarySchema = {
    properties: {
        totals: {
            '$ref': '#/components/schemas/MetricTotals'
        },
        by_platform: {
            additionalProperties: {
                '$ref': '#/components/schemas/MetricTotals'
            },
            type: 'object',
            title: 'By Platform'
        },
        date_from: {
            type: 'string',
            format: 'date',
            title: 'Date From'
        },
        date_to: {
            type: 'string',
            format: 'date',
            title: 'Date To'
        }
    },
    type: 'object',
    required: ['totals', 'by_platform', 'date_from', 'date_to'],
    title: 'MetricsSummary',
    description: 'Response for GET /metrics/summary.'
} as const;

export const MetricsTimeSeriesSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TimeSeriesPoint'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'MetricsTimeSeries',
    description: 'Response for GET /metrics/timeseries.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PlatformSchema = {
    type: 'string',
    enum: ['facebook', 'instagram', 'twitter', 'linkedin', 'tiktok', 'google_analytics'],
    title: 'Platform'
} as const;

export const PlatformAccountPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        integration_id: {
            type: 'string',
            format: 'uuid',
            title: 'Integration Id'
        },
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        },
        platform: {
            '$ref': '#/components/schemas/Platform'
        },
        external_id: {
            type: 'string',
            title: 'External Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        account_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Type'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'integration_id', 'workspace_id', 'platform', 'external_id', 'name', 'is_active'],
    title: 'PlatformAccountPublic'
} as const;

export const PlatformAccountsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlatformAccountPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlatformAccountsPublic'
} as const;

export const PostPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        platform_account_id: {
            type: 'string',
            format: 'uuid',
            title: 'Platform Account Id'
        },
        external_id: {
            type: 'string',
            title: 'External Id'
        },
        published_at: {
            type: 'string',
            format: 'date-time',
            title: 'Published At'
        },
        content_type: {
            '$ref': '#/components/schemas/ContentType'
        },
        text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Text'
        },
        media_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Url'
        },
        permalink: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Permalink'
        },
        impressions: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Impressions'
        },
        reach: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reach'
        },
        views: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Views'
        },
        engagements: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Engagements'
        },
        likes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Likes'
        },
        comments: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comments'
        },
        shares: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shares'
        },
        clicks: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Clicks'
        },
        saves: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Saves'
        },
        engagement_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Engagement Rate'
        }
    },
    type: 'object',
    required: ['id', 'platform_account_id', 'external_id', 'published_at', 'content_type'],
    title: 'PostPublic'
} as const;

export const PostsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PostPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PostsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ReportResponseSchema = {
    properties: {
        report: {
            type: 'string',
            title: 'Report'
        },
        generated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Generated At'
        }
    },
    type: 'object',
    required: ['report'],
    title: 'ReportResponse'
} as const;

export const TimeSeriesPointSchema = {
    properties: {
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        impressions: {
            type: 'integer',
            title: 'Impressions',
            default: 0
        },
        reach: {
            type: 'integer',
            title: 'Reach',
            default: 0
        },
        views: {
            type: 'integer',
            title: 'Views',
            default: 0
        },
        clicks: {
            type: 'integer',
            title: 'Clicks',
            default: 0
        },
        engagements: {
            type: 'integer',
            title: 'Engagements',
            default: 0
        }
    },
    type: 'object',
    required: ['date'],
    title: 'TimeSeriesPoint'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WorkspaceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'WorkspaceCreate'
} as const;

export const WorkspaceMemberAddSchema = {
    properties: {
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        role: {
            '$ref': '#/components/schemas/WorkspaceRole',
            default: 'viewer'
        }
    },
    type: 'object',
    title: 'WorkspaceMemberAdd',
    description: 'Identify the user to add by id or by the email they signed up with.'
} as const;

export const WorkspaceMemberPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        role: {
            '$ref': '#/components/schemas/WorkspaceRole'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        user_email: {
            type: 'string',
            title: 'User Email'
        },
        user_full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Full Name'
        }
    },
    type: 'object',
    required: ['user_id', 'role', 'user_email'],
    title: 'WorkspaceMemberPublic'
} as const;

export const WorkspaceMemberUpdateSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/WorkspaceRole'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'WorkspaceMemberUpdate'
} as const;

export const WorkspaceMembersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkspaceMemberPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkspaceMembersPublic'
} as const;

export const WorkspacePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        role: {
            '$ref': '#/components/schemas/WorkspaceRole'
        }
    },
    type: 'object',
    required: ['id', 'name', 'slug', 'role'],
    title: 'WorkspacePublic'
} as const;

export const WorkspaceRoleSchema = {
    type: 'string',
    enum: ['owner', 'admin', 'viewer'],
    title: 'WorkspaceRole'
} as const;

export const WorkspaceUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        }
    },
    type: 'object',
    title: 'WorkspaceUpdate'
} as const;

export const WorkspacesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkspacePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkspacesPublic'
} as const;