// This file is auto-generated by @hey-api/openapi-ts

/**
 * Common fields for AI generation requests.
 */
export type AIRequest = {
    workspace_id: string;
    platform?: (Platform | null);
    date_from?: (string | null);
    date_to?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContentType = 'post' | 'reel' | 'story' | 'video' | 'tweet' | 'article' | 'short';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Insight = {
    title: string;
    body: string;
    type: 'positive' | 'negative' | 'neutral';
    metric?: (string | null);
};

export type type = 'positive' | 'negative' | 'neutral';

export type InsightsResponse = {
    insights: Array<Insight>;
    generated_at?: string;
};

/**
 * Safe representation — never includes raw or encrypted tokens.
 */
export type IntegrationPublic = {
    id: string;
    workspace_id: string;
    platform: Platform;
    status: IntegrationStatus;
    external_account_id: string;
    external_account_name: string;
    external_account_avatar?: (string | null);
    last_synced_at?: (string | null);
    sync_error?: (string | null);
    created_at?: (string | null);
};

export type IntegrationsPublic = {
    data: Array<IntegrationPublic>;
    count: number;
};

export type IntegrationStatus = 'active' | 'expired' | 'error' | 'disconnected';

export type Message = {
    message: string;
};

/**
 * Response for GET /metrics/summary.
 */
export type MetricsSummary = {
    totals: MetricTotals;
    by_platform: {
        [key: string]: MetricTotals;
    };
    date_from: string;
    date_to: string;
};

/**
 * Response for GET /metrics/timeseries.
 */
export type MetricsTimeSeries = {
    data: Array<TimeSeriesPoint>;
};

/**
 * Aggregated metric totals over a date range.
 */
export type MetricTotals = {
    impressions?: number;
    reach?: number;
    views?: number;
    clicks?: number;
    engagements?: number;
    likes?: number;
    comments?: number;
    shares?: number;
    saves?: number;
    followers_count?: (number | null);
    followers_gained?: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type Platform = 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'tiktok' | 'google_analytics';

export type PlatformAccountPublic = {
    id: string;
    integration_id: string;
    workspace_id: string;
    platform: Platform;
    external_id: string;
    name: string;
    avatar_url?: (string | null);
    account_type?: (string | null);
    is_active: boolean;
    created_at?: (string | null);
};

export type PlatformAccountsPublic = {
    data: Array<PlatformAccountPublic>;
    count: number;
};

export type PostPublic = {
    id: string;
    platform_account_id: string;
    external_id: string;
    published_at: string;
    content_type: ContentType;
    text?: (string | null);
    media_url?: (string | null);
    permalink?: (string | null);
    impressions?: (number | null);
    reach?: (number | null);
    views?: (number | null);
    engagements?: (number | null);
    likes?: (number | null);
    comments?: (number | null);
    shares?: (number | null);
    clicks?: (number | null);
    saves?: (number | null);
    engagement_rate?: (number | null);
};

export type PostsPublic = {
    data: Array<PostPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReportResponse = {
    report: string;
    generated_at?: string;
};

export type TimeSeriesPoint = {
    date: string;
    impressions?: number;
    reach?: number;
    views?: number;
    clicks?: number;
    engagements?: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WorkspaceCreate = {
    name: string;
    slug?: (string | null);
};

/**
 * Identify the user to add by id or by the email they signed up with.
 */
export type WorkspaceMemberAdd = {
    user_id?: (string | null);
    email?: (string | null);
    role?: WorkspaceRole;
};

export type WorkspaceMemberPublic = {
    user_id: string;
    role: WorkspaceRole;
    created_at?: (string | null);
    user_email: string;
    user_full_name?: (string | null);
};

export type WorkspaceMembersPublic = {
    data: Array<WorkspaceMemberPublic>;
    count: number;
};

export type WorkspaceMemberUpdate = {
    role: WorkspaceRole;
};

export type WorkspacePublic = {
    id: string;
    name: string;
    slug: string;
    created_at?: (string | null);
    role: WorkspaceRole;
};

export type WorkspaceRole = 'owner' | 'admin' | 'viewer';

export type WorkspacesPublic = {
    data: Array<WorkspacePublic>;
    count: number;
};

export type WorkspaceUpdate = {
    name?: (string | null);
    slug?: (string | null);
};

export type AiGenerateInsightsData = {
    requestBody: AIRequest;
};

export type AiGenerateInsightsResponse = (InsightsResponse);

export type AiGenerateReportData = {
    requestBody: AIRequest;
};

export type AiGenerateReportResponse = (ReportResponse);

export type IntegrationsListIntegrationsData = {
    platform?: (Platform | null);
    workspaceId: string;
};

export type IntegrationsListIntegrationsResponse = (IntegrationsPublic);

export type IntegrationsGetIntegrationData = {
    integrationId: string;
};

export type IntegrationsGetIntegrationResponse = (IntegrationPublic);

export type IntegrationsDeleteIntegrationData = {
    integrationId: string;
};

export type IntegrationsDeleteIntegrationResponse = (Message);

export type IntegrationsListAccountsData = {
    integrationId: string;
};

export type IntegrationsListAccountsResponse = (PlatformAccountsPublic);

export type IntegrationsTriggerSyncData = {
    integrationId: string;
};

export type IntegrationsTriggerSyncResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MetricsGetSummaryData = {
    dateFrom?: string;
    dateTo?: string;
    platform?: (Platform | null);
    workspaceId: string;
};

export type MetricsGetSummaryResponse = (MetricsSummary);

export type MetricsGetTimeseriesData = {
    dateFrom?: string;
    dateTo?: string;
    platform?: (Platform | null);
    workspaceId: string;
};

export type MetricsGetTimeseriesResponse = (MetricsTimeSeries);

export type MetricsGetTopPostsData = {
    dateFrom?: string;
    dateTo?: string;
    limit?: number;
    platform?: (Platform | null);
    workspaceId: string;
};

export type MetricsGetTopPostsResponse = (PostsPublic);

export type OauthConnectData = {
    platform: Platform;
    workspaceId: string;
};

export type OauthConnectResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WorkspacesCreateWorkspaceData = {
    requestBody: WorkspaceCreate;
};

export type WorkspacesCreateWorkspaceResponse = (WorkspacePublic);

export type WorkspacesListWorkspacesData = {
    limit?: number;
    skip?: number;
};

export type WorkspacesListWorkspacesResponse = (WorkspacesPublic);

export type WorkspacesGetWorkspaceData = {
    workspaceId: string;
};

export type WorkspacesGetWorkspaceResponse = (WorkspacePublic);

export type WorkspacesUpdateWorkspaceData = {
    requestBody: WorkspaceUpdate;
    workspaceId: string;
};

export type WorkspacesUpdateWorkspaceResponse = (WorkspacePublic);

export type WorkspacesDeleteWorkspaceData = {
    workspaceId: string;
};

export type WorkspacesDeleteWorkspaceResponse = (Message);

export type WorkspacesListMembersData = {
    workspaceId: string;
};

export type WorkspacesListMembersResponse = (WorkspaceMembersPublic);

export type WorkspacesAddMemberData = {
    requestBody: WorkspaceMemberAdd;
    workspaceId: string;
};

export type WorkspacesAddMemberResponse = (WorkspaceMemberPublic);

export type WorkspacesUpdateMemberData = {
    requestBody: WorkspaceMemberUpdate;
    userId: string;
    workspaceId: string;
};

export type WorkspacesUpdateMemberResponse = (WorkspaceMemberPublic);

export type WorkspacesRemoveMemberData = {
    userId: string;
    workspaceId: string;
};

export type WorkspacesRemoveMemberResponse = (Message);