// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContentType = 'post' | 'reel' | 'story' | 'video' | 'tweet' | 'article' | 'short';

export type FollowersPoint = {
    date: string;
    followers: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Insight = {
    title: string;
    body: string;
    type: 'positive' | 'negative' | 'neutral';
    metric?: (string | null);
};

export type type = 'positive' | 'negative' | 'neutral';

export type InsightsResponse = {
    insights: Array<Insight>;
    generated_at?: string;
};

/**
 * Safe representation — never includes raw or encrypted tokens.
 */
export type IntegrationPublic = {
    id: string;
    workspace_id: string;
    platform: Platform;
    status: IntegrationStatus;
    external_account_id: string;
    external_account_name: string;
    external_account_avatar?: (string | null);
    last_synced_at?: (string | null);
    sync_error?: (string | null);
    created_at?: (string | null);
};

export type IntegrationStatus = 'active' | 'expired' | 'error' | 'disconnected';

/**
 * How a metric is distributed across a platform's post history.
 */
export type MetricBenchmark = {
    sample_size: number;
    p5: number;
    p50: number;
    p95: number;
};

/**
 * Overall and per-platform totals over a date range.
 */
export type MetricsSummary = {
    totals: MetricTotals;
    by_platform: {
        [key: string]: MetricTotals;
    };
    date_from: string;
    date_to: string;
};

/**
 * Aggregated metric totals over a date range. A metric none of the accounts
 * reports is None, as opposed to 0 when it was reported as zero.
 */
export type MetricTotals = {
    exposures?: (number | null);
    impressions?: (number | null);
    reach?: (number | null);
    views?: (number | null);
    clicks?: (number | null);
    engagements?: (number | null);
    likes?: (number | null);
    comments?: (number | null);
    shares?: (number | null);
    saves?: (number | null);
    followers_count?: (number | null);
    followers_gained?: (number | null);
    followers_growth?: (number | null);
    followers_growth_rate?: (number | null);
    engagement_rate?: (number | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Where to send the user to authorize the platform.
 */
export type OAuthConnectResponse = {
    authorization_url: string;
};

export type Platform = 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'tiktok' | 'google_analytics';

/**
 * A platform's follower count per day: the sum over its accounts of their
 * latest count up to that day. Days before any count are left out.
 */
export type PlatformFollowers = {
    platform: Platform;
    points: Array<FollowersPoint>;
};

/**
 * A post's metrics only, for plotting the history over time.
 */
export type PostHistoryPoint = {
    impressions?: (number | null);
    reach?: (number | null);
    views?: (number | null);
    engagements?: (number | null);
    likes?: (number | null);
    comments?: (number | null);
    shares?: (number | null);
    clicks?: (number | null);
    saves?: (number | null);
    id: string;
    published_at: string;
    engagement_rate?: (number | null);
};

/**
 * A recent post, situated within the platform's post history.
 */
export type PostPerformance = {
    impressions?: (number | null);
    reach?: (number | null);
    views?: (number | null);
    engagements?: (number | null);
    likes?: (number | null);
    comments?: (number | null);
    shares?: (number | null);
    clicks?: (number | null);
    saves?: (number | null);
    external_id: string;
    content_type: ContentType;
    text?: (string | null);
    media_url?: (string | null);
    permalink?: (string | null);
    id: string;
    platform_account_id: string;
    platform: Platform;
    published_at: string;
    engagement_rate?: (number | null);
    percentile_ranks: {
        [key: string]: (number);
    };
};

/**
 * One platform's latest posts, compared with its own post history.
 */
export type PostPerformanceReport = {
    platform: Platform;
    history_from: string;
    history_to: string;
    history_size: number;
    benchmarks: {
        [key: string]: MetricBenchmark;
    };
    posts: Array<PostPerformance>;
    history: Array<PostHistoryPoint>;
};

export type PostPublic = {
    impressions?: (number | null);
    reach?: (number | null);
    views?: (number | null);
    engagements?: (number | null);
    likes?: (number | null);
    comments?: (number | null);
    shares?: (number | null);
    clicks?: (number | null);
    saves?: (number | null);
    external_id: string;
    content_type: ContentType;
    text?: (string | null);
    media_url?: (string | null);
    permalink?: (string | null);
    id: string;
    platform_account_id: string;
    platform: Platform;
    published_at: string;
    engagement_rate?: (number | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReportResponse = {
    report: string;
    generated_at?: string;
};

export type TimeSeriesPoint = {
    date: string;
    exposures?: number;
    impressions?: number;
    reach?: number;
    views?: number;
    clicks?: number;
    engagements?: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WorkspaceCreate = {
    name: string;
    slug?: (string | null);
};

/**
 * An existing user to add, identified by the email they signed up with.
 */
export type WorkspaceMemberAdd = {
    email: string;
    role?: WorkspaceRole;
};

export type WorkspaceMemberPublic = {
    user_id: string;
    role: WorkspaceRole;
    created_at?: (string | null);
    user_email: string;
    user_full_name?: (string | null);
};

export type WorkspaceMemberUpdate = {
    role: WorkspaceRole;
};

export type WorkspacePublic = {
    id: string;
    name: string;
    slug: string;
    created_at?: (string | null);
    role: WorkspaceRole;
};

export type WorkspaceRole = 'owner' | 'admin' | 'viewer';

export type WorkspaceUpdate = {
    name?: (string | null);
    slug?: (string | null);
};

export type AiGenerateInsightsData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    platform?: (Platform | null);
    workspaceId: string;
};

export type AiGenerateInsightsResponse = (InsightsResponse);

export type AiGenerateReportData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    platform?: (Platform | null);
    workspaceId: string;
};

export type AiGenerateReportResponse = (ReportResponse);

export type IntegrationsListIntegrationsData = {
    workspaceId: string;
};

export type IntegrationsListIntegrationsResponse = (Array<IntegrationPublic>);

export type IntegrationsConnectData = {
    platform: Platform;
    workspaceId: string;
};

export type IntegrationsConnectResponse = (OAuthConnectResponse);

export type IntegrationsDeleteIntegrationData = {
    integrationId: string;
    workspaceId: string;
};

export type IntegrationsDeleteIntegrationResponse = (void);

export type IntegrationsTriggerSyncData = {
    integrationId: string;
    workspaceId: string;
};

export type IntegrationsTriggerSyncResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (unknown);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (void);

export type MetricsGetSummaryData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    platform?: (Platform | null);
    workspaceId: string;
};

export type MetricsGetSummaryResponse = (MetricsSummary);

export type MetricsGetTimeseriesData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    platform?: (Platform | null);
    workspaceId: string;
};

export type MetricsGetTimeseriesResponse = (Array<TimeSeriesPoint>);

export type MetricsGetFollowersData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    platform?: (Platform | null);
    workspaceId: string;
};

export type MetricsGetFollowersResponse = (Array<PlatformFollowers>);

export type MetricsGetTopPostsData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    limit?: number;
    platform?: (Platform | null);
    workspaceId: string;
};

export type MetricsGetTopPostsResponse = (Array<PostPublic>);

export type MetricsGetPostPerformanceData = {
    historyDays?: number;
    limit?: number;
    platform?: (Platform | null);
    workspaceId: string;
};

export type MetricsGetPostPerformanceResponse = (Array<PostPerformanceReport>);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersResponse = (Array<UserPublic>);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (void);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (void);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (void);

export type UtilsHealthCheckResponse = (boolean);

export type WorkspacesListWorkspacesResponse = (Array<WorkspacePublic>);

export type WorkspacesCreateWorkspaceData = {
    requestBody: WorkspaceCreate;
};

export type WorkspacesCreateWorkspaceResponse = (WorkspacePublic);

export type WorkspacesUpdateWorkspaceData = {
    requestBody: WorkspaceUpdate;
    workspaceId: string;
};

export type WorkspacesUpdateWorkspaceResponse = (WorkspacePublic);

export type WorkspacesDeleteWorkspaceData = {
    workspaceId: string;
};

export type WorkspacesDeleteWorkspaceResponse = (void);

export type WorkspacesListMembersData = {
    workspaceId: string;
};

export type WorkspacesListMembersResponse = (Array<WorkspaceMemberPublic>);

export type WorkspacesAddMemberData = {
    requestBody: WorkspaceMemberAdd;
    workspaceId: string;
};

export type WorkspacesAddMemberResponse = (WorkspaceMemberPublic);

export type WorkspacesUpdateMemberData = {
    requestBody: WorkspaceMemberUpdate;
    userId: string;
    workspaceId: string;
};

export type WorkspacesUpdateMemberResponse = (WorkspaceMemberPublic);

export type WorkspacesRemoveMemberData = {
    userId: string;
    workspaceId: string;
};

export type WorkspacesRemoveMemberResponse = (void);