"""Database access helpers, re-exported so callers can use ``crud.<name>``."""

from app.crud.analysis import (
    get_analyses,
    get_analysis,
    get_due_schedules,
    get_schedule,
    has_unfinished_analysis,
)
from app.crud.common import (
    delete,
    save,
)
from app.crud.integration import (
    get_access_token,
    get_accounts_for_workspace,
    get_integration,
    get_integrations_for_workspace,
    get_refresh_token,
    mark_integration_error,
    mark_integration_expired,
    mark_integration_synced,
    update_integration_tokens,
    upsert_integration,
    upsert_platform_account,
)
from app.crud.metrics import (
    get_posts,
    get_posts_by_ids,
    get_posts_for_accounts,
    get_snapshots_for_accounts,
    get_top_posts,
    merge_imported_posts,
    merge_imported_snapshots,
    upsert_metric_snapshot,
    upsert_post,
)
from app.crud.migration import get_migrations, has_unfinished_migration
from app.crud.user import (
    authenticate,
    create_user,
    get_user_by_email,
    get_user_by_email_case_insensitive,
    update_user,
)
from app.crud.workspace import (
    add_member,
    count_owners,
    create_workspace,
    get_member,
    get_members,
    get_memberships_for_user,
    get_workspace,
    update_member_role,
    update_workspace,
)

__all__ = [
    "add_member",
    "authenticate",
    "count_owners",
    "create_user",
    "create_workspace",
    "delete",
    "get_access_token",
    "get_accounts_for_workspace",
    "get_analyses",
    "get_analysis",
    "get_due_schedules",
    "get_integration",
    "get_integrations_for_workspace",
    "get_member",
    "get_members",
    "get_memberships_for_user",
    "get_migrations",
    "get_posts",
    "get_posts_by_ids",
    "get_refresh_token",
    "get_posts_for_accounts",
    "get_schedule",
    "get_snapshots_for_accounts",
    "get_top_posts",
    "get_user_by_email",
    "get_user_by_email_case_insensitive",
    "get_workspace",
    "has_unfinished_analysis",
    "has_unfinished_migration",
    "mark_integration_error",
    "mark_integration_expired",
    "mark_integration_synced",
    "merge_imported_posts",
    "merge_imported_snapshots",
    "save",
    "update_integration_tokens",
    "update_member_role",
    "update_user",
    "update_workspace",
    "upsert_integration",
    "upsert_metric_snapshot",
    "upsert_platform_account",
    "upsert_post",
]
