"""Add integration and platformaccount tables

Revision ID: 34d3466d0af0
Revises: 5cdd5982405c
Create Date: 2026-04-02 13:04:54.748125

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34d3466d0af0'
down_revision = '5cdd5982405c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'twitter', 'linkedin', 'tiktok', 'google_analytics', name='platform'), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'error', 'disconnected', name='integrationstatus'), nullable=False),
    sa.Column('access_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_account_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('external_account_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('external_account_avatar', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_workspace_id'), 'integration', ['workspace_id'], unique=False)
    op.create_table('platformaccount',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'twitter', 'linkedin', 'tiktok', 'google_analytics', name='platform'), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platformaccount_external_id'), 'platformaccount', ['external_id'], unique=False)
    op.create_index(op.f('ix_platformaccount_integration_id'), 'platformaccount', ['integration_id'], unique=False)
    op.create_index(op.f('ix_platformaccount_workspace_id'), 'platformaccount', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platformaccount_workspace_id'), table_name='platformaccount')
    op.drop_index(op.f('ix_platformaccount_integration_id'), table_name='platformaccount')
    op.drop_index(op.f('ix_platformaccount_external_id'), table_name='platformaccount')
    op.drop_table('platformaccount')
    op.drop_index(op.f('ix_integration_workspace_id'), table_name='integration')
    op.drop_table('integration')
    # ### end Alembic commands ###
