"""Add migration table

Revision ID: 56ccfad11eb7
Revises: 7b1c2e9d4f30
Create Date: 2026-10-05 20:41:41.128371

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '56ccfad11eb7'
down_revision = '7b1c2e9d4f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('sprout_social', 'metricool', name='migrationsource'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='migrationstatus'), nullable=False),
    sa.Column('credentials_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('profiles', sa.JSON(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_workspace_id'), 'migration', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_migration_workspace_id'), table_name='migration')
    op.drop_table('migration')
    sa.Enum(name='migrationstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='migrationsource').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
