"""Add performance analysis and analysis schedule tables

Revision ID: 5ce89f0c2b24
Revises: c4e2a9d7f1b3
Create Date: 2026-10-02 07:53:51.849324

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5ce89f0c2b24'
down_revision = 'c4e2a9d7f1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysisschedule',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'biweekly', 'monthly', name='analysisfrequency'), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_recipients', sa.JSON(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('performanceanalysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('trigger', sa.Enum('manual', 'scheduled', name='analysistrigger'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='analysisstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performanceanalysis_workspace_id'), 'performanceanalysis', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performanceanalysis_workspace_id'), table_name='performanceanalysis')
    op.drop_table('performanceanalysis')
    op.drop_table('analysisschedule')
    # ### end Alembic commands ###
    for enum in ('analysisstatus', 'analysistrigger', 'analysisfrequency'):
        sa.Enum(name=enum).drop(op.get_bind(), checkfirst=True)
