"""Add metricsnapshot and post tables

Revision ID: b5400ce9ef4f
Revises: 34d3466d0af0
Create Date: 2026-04-02 13:13:37.683789

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b5400ce9ef4f'
down_revision = '34d3466d0af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricsnapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform_account_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('followers_gained', sa.Integer(), nullable=True),
    sa.Column('followers_lost', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('engagements', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platformaccount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_account_id', 'date', name='uq_metricsnapshot_account_date')
    )
    op.create_index(op.f('ix_metricsnapshot_platform_account_id'), 'metricsnapshot', ['platform_account_id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform_account_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_type', sa.Enum('post', 'reel', 'story', 'video', 'tweet', 'article', 'short', name='contenttype'), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('permalink', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('engagements', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platformaccount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_account_id', 'external_id', name='uq_post_account_external_id')
    )
    op.create_index(op.f('ix_post_platform_account_id'), 'post', ['platform_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_platform_account_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_metricsnapshot_platform_account_id'), table_name='metricsnapshot')
    op.drop_table('metricsnapshot')
    # ### end Alembic commands ###
